alias ls='ls --color=auto'
alias l='ls -lahF'
#alias l='exa -lag'
alias gr='sudo pacman -Rsdd'
alias gs='sudo pacman -Ssq'
alias g='sudo pacman -S'
alias gg='sudo pacman -Sy'
alias ggg='sudo pacman -Scc'
alias i='makepkg -si'
alias e='vim ~/.config/i3/config'
alias m='cd ~/music'
alias r='ranger'
alias p='mpv --no-video'
alias ggu='sudo pacman -Syu'
alias gu='sudo pacman -Su'
alias c='cd ~/Downloads'
alias v='vim'
alias ri='ristretto'
alias u='sudo umount /mnt'
alias gy='sudo pacman -S --noconfirm'
alias o='bpytop'
alias df='duf'
alias find='fd -H'
alias tree='dust -b'
alias w='curl wttr.in'
setxkbmap -option "caps:swapescape"
