#! /usr/bin/env python3
from os import system
def checker():
	system('ps x|grep "unclutter --timeout 3">/tmp/asiod')
	if len(open('/tmp/asiod').readlines())<3:
		open('/tmp/jiol','w').write('0')
	else:
		open('/tmp/jiol','w').write('1')
def exe():
	if open('/tmp/jiol','r').read()=='1':
		system('killall unclutter')
		open('/tmp/hgiureo','w').write('1')
	elif open('/tmp/jiol','r').read()=='0':
		system('unclutter --timeout 3 &')
		open('/tmp/hgiureo','w').write('0')
checker()
exe()
